# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: unikernel-test
  region: eu-north-1
  version: "1.30"
vpc:
  cidr: 10.173.0.0/16
  clusterEndpoints:
    privateAccess: true
    publicAccess: true  
  publicAccessCIDRs: ["213.233.88.0/24", "213.233.88.150/32"]  
managedNodeGroups:
  - name: managed-ng-test-1
    instanceType: m5.xlarge
    amiFamily: Ubuntu2204
      #ami: ami-053f81caf652e695c
      #overrideBootstrapCommand: |
      #  #!/bin/bash

      #  source /var/lib/cloud/scripts/eksctl/bootstrap.helper.sh

      #  # CLUSTER_NAME="unikernel-test"
      #  # NODE_LABELS="alpha.eksctl.io/cluster-name=unikernel-test,alpha.eksctl.io/nodegroup-name=managed-ng-test-1"

      #  /etc/eks/bootstrap.sh ${CLUSTER_NAME} --container-runtime containerd --kubelet-extra-args "--node-labels=${NODE_LABELS}"
    minSize: 1
    maxSize: 3
    desiredCapacity: 1
    volumeSize: 73
    ssh:
      publicKeyPath: ~/.ssh/id_rsa-unikernel-test.pub
    labels:
      alpha.eksctl.io/cluster-name: unikernel-test
      alpha.eksctl.io/nodegroup-name: managed-ng-test-1
iam:
  withOIDC: true
