# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: unikernel-test
  region: eu-north-1
  version: "1.30"
vpc:
  cidr: 10.173.0.0/16
  clusterEndpoints:
    privateAccess: true
    publicAccess: true  
  publicAccessCIDRs: ["213.233.88.0/24", "213.233.88.150/32"]  
iam:
  withOIDC: true
