apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"admissionregistration.k8s.io/v1","kind":"ValidatingWebhookConfiguration","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"webhook","app.kubernetes.io/name":"knative-serving","app.kubernetes.io/version":"1.14.1"},"name":"config.webhook.serving.knative.dev"},"webhooks":[{"admissionReviewVersions":["v1","v1beta1"],"clientConfig":{"service":{"name":"webhook","namespace":"knative-serving"}},"failurePolicy":"Fail","name":"config.webhook.serving.knative.dev","objectSelector":{"matchExpressions":[{"key":"app.kubernetes.io/name","operator":"In","values":["knative-serving"]},{"key":"app.kubernetes.io/component","operator":"In","values":["autoscaler","controller","logging","networking","observability","tracing"]}]},"sideEffects":"None","timeoutSeconds":10}]}
  creationTimestamp: "2024-06-13T07:37:31Z"
  generation: 2
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: 1.14.1
  name: config.webhook.serving.knative.dev
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Namespace
    name: knative-serving
    uid: 3415e5c9-d210-46b9-89a9-eb85f46c5f1a
  resourceVersion: "223620"
  uid: f38da9ca-dadc-47e4-ad93-14851be168af
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNUakNDQWZTZ0F3SUJBZ0lRUHRTUGlnT0NFSzVTT1VJaERJVzcrVEFLQmdncWhrak9QUVFEQWpBOE1SUXcKRWdZRFZRUUtFd3RyYm1GMGFYWmxMbVJsZGpFa01DSUdBMVVFQXhNYmQyVmlhRzl2YXk1cmJtRjBhWFpsTFhObApjblpwYm1jdWMzWmpNQjRYRFRJME1EWXhNekEzTkRreE9Wb1hEVEkwTURZeU1EQTNORGt4T1Zvd1BERVVNQklHCkExVUVDaE1MYTI1aGRHbDJaUzVrWlhZeEpEQWlCZ05WQkFNVEczZGxZbWh2YjJzdWEyNWhkR2wyWlMxelpYSjIKYVc1bkxuTjJZekJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCSzVQOUVmZWNiS2EyRkY2NWZtNApodlV3Nnh6MzdjOExPandYMlpUQWpFV3BsSjdrNEc2anIxSGNPc2twWHg2Ym5ncXNPYVJUbEtNSFJpeGlxTnhmCkI1bWpnZGN3Z2RRd0RnWURWUjBQQVFIL0JBUURBZ0tFTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3IKQmdFRkJRY0RBakFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlEwQkJlYUt0bVcwYWZUU2ljegp1anMxaEdjYTNEQnpCZ05WSFJFRWJEQnFnZ2QzWldKb2IyOXJnaGQzWldKb2IyOXJMbXR1WVhScGRtVXRjMlZ5CmRtbHVaNEliZDJWaWFHOXZheTVyYm1GMGFYWmxMWE5sY25acGJtY3VjM1pqZ2lsM1pXSm9iMjlyTG10dVlYUnAKZG1VdGMyVnlkbWx1Wnk1emRtTXVZMngxYzNSbGNpNXNiMk5oYkRBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQQovd1p0UkNESld2THlHNWQrRjY1ZmRrbUFycDRpYVF6VGlKY2ZZSEdFY2dNQ0lFTnVvdDdQWS9vcnpwOVFLWTA1ClVjTEZXK2FIUENBcnZNdHN2L1c0aGgyLwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: webhook
      namespace: knative-serving
      path: /config-validation
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: config.webhook.serving.knative.dev
  namespaceSelector: {}
  objectSelector:
    matchExpressions:
    - key: app.kubernetes.io/name
      operator: In
      values:
      - knative-serving
    - key: app.kubernetes.io/component
      operator: In
      values:
      - autoscaler
      - controller
      - logging
      - networking
      - observability
      - tracing
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - configmaps/*
    scope: Namespaced
  sideEffects: None
  timeoutSeconds: 10
