apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: nginx-urunc
spec:
  template:
    spec:
      runtimeClassName: urunc
      containers:
        - image: harbor.nbfc.io/nubificus/urunc/nginx-qemu-unikraft:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              port: 80
              path: "/"
